#!/usr/bin/env bash
# osx dmenu clone (https://github.com/sdegutis/choose) feeding script

SEARCH_PATH=(/Applications "$HOME/Applications" /Applications/Utilities)

apps=$(find "${SEARCH_PATH[@]}" -maxdepth 1 -name '*.app' \
	| sed 's:.*/\(.*\)\.app:\1:' \
	| sort -u)

PREFERENCES_PATH=(/System/Library/PreferencePanes)

preferences=$(find "${PREFERENCES_PATH[@]}" -maxdepth 1 -name '*.prefPane' \
	| sed 's:.*/\(.*\)\.prefPane:\1:' \
	| sort -u)

apps="$apps $preferences"

to_run=$(cat <(echo "$apps") | /usr/local/bin/choose "$@")
if [[ -z $to_run ]]; then
	exit
fi

if grep "$to_run" <<<"$preferences" &>/dev/null; then
	open "/System/Library/PreferencePanes/$to_run.prefPane/"
elif grep "$to_run" <<<"$apps" &>/dev/null; then
	open -a "$to_run" -n
else
	echo "$to_run" | ${SHELL:-"/bin/sh"}
fi
