gaps:
  inner_gap: 8
  outer_gap: 8

general:
  # Whether to show floating windows as always on top.
  show_floating_on_top: false

bar:
  height: "25px"
  position: "top"
  opacity: 1.0
  background: "#222222"
  foreground: "#ffffff"
  font_family: "Segoe UI"
  font_size: "13px"
  padding: "2px 6px"
  offset_x: "0"
  offset_y: "0"
  border_radius: "0"
  components_left:
    - type: "workspaces"
      focused_workspace_background: "#ffffff33"
      displayed_workspace_background: "#00000033"
      default_workspace_background: "transparent"
  components_right:
    - type: "binding mode"
      background: "#ffffff33"
      margin: "0 4px 0 0"
      padding: "0 8px"
    - type: "tiling direction"
      label_horizontal: "⮂"
      label_vertical: "⮁"
      padding: "0 8px"

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  # Task Manager requires admin privileges to manage and should be ignored unless running
  # the WM as admin.
  - command: "ignore"
    match_process_name: "Taskmgr"

  # Launches system dialogs as floating by default (eg. File Explorer save/open dialog).
  - command: "set floating"
    match_class_name: "#32770"

  # Some applications (eg. Steam) have borders that extend past the normal border size.
  - command: "resize borders 0px -7px -7px -7px"
    match_process_name: "steam"
  - command: set floating
    match_process_name: 1Password
  - command: set floating
    match_title: Window Spy
  - command: set floating
    match_process_name: Bloxstrap
  - command: set floating
    match_title: Calculator
  - command: set floating
    match_process_name: CredentialUIBroker
  - command: set floating
    match_class_name: TApplication
  - command: set floating
    match_class_name: TWizardForm
  - command: set floating
    match_process_name: Camera Hub
  - command: set floating
    match_process_name: ControlCenter
  - command: set floating
    match_process_name: WaveLink
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: keyviz
  - command: set floating
    match_process_name: LogiBolt
  - command: set floating
    match_process_name: LogiTune
  - command: set floating
    match_process_name: LogiOptionsUI
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_process_name: MSPCManager
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_title: Microsoft Teams Notification
  - command: set floating
    match_title: Microsoft Teams Call
  - command: set floating
    match_class_name: _WwB
  - command: set floating
    match_class_name: MozillaTaskbarPreviewClass
  - command: set floating
    match_process_name: NohBoard
  - command: set floating
    match_process_name: Paradox Launcher
  - command: set floating
    match_process_name: PowerToys.ColorPickerUI
  - command: set floating
    match_process_name: PowerToys.ImageResizer
  - command: set floating
    match_process_name: ProcessHacker
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: QuickLook
  - command: set floating
    match_process_name: RepoZ
  - command: set floating
    match_class_name: SunAwtDialog
  - command: set floating
    match_process_name: RoundedTB
  - command: set floating
    match_process_name: sideloadly
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: Chrome_RenderWidgetHostHWND
  - command: set floating
    match_class_name: obj_App
  - command: set floating
    match_class_name: obj_Form
  - command: set floating
    match_process_name: SystemInformer
  - command: set floating
    match_class_name: Shell_Dialog
  - command: set floating
    match_class_name: TaskManagerWindow
  - command: set floating
    match_process_name: tcconfig
  - command: set floating
    match_process_name: TranslucentTB
  - command: set floating
    match_class_name: OperationStatusWindow
  - command: set floating
    match_title: Control Panel
  - command: set floating
    match_process_name: msiexec
  - command: set floating
    match_title: Hotkey sink
  - command: set floating
    match_process_name: Zoom
  - command: set floating
    match_process_name: paintdotnet
  - command: set floating
    match_process_name: pinentry
  - command: set floating
    match_process_name: ueli

binding_modes:
  - name: "resize"
    keybindings:
      # Resize focused window by a percentage or pixel amount.
      - command: "resize width -4%"
        bindings: ["H", "Left"]
      - command: "resize width +4%"
        bindings: ["L", "Right"]
      - command: "resize height +4%"
        bindings: ["K", "Up"]
      - command: "resize height -4%"
        bindings: ["J", "Down"]
      # Press enter/escape to return to default keybindings.
      - command: "binding mode none"
        bindings: ["Escape", "Enter"]

keybindings:
  # Shift focus in a given direction.
  - command: "focus left"
    bindings: ["LWin+Left"]
  - command: "focus right"
    bindings: ["LWin+Right"]
  - command: "focus up"
    bindings: ["LWin+Up"]
  - command: "focus down"
    bindings: ["LWin+Down"]

  # Move focused window in a given direction.
  - command: "move left"
    bindings: ["LWin+Shift+Left", "Alt+Shift+Left"]
  - command: "move right"
    bindings: ["LWin+Shift+Right", "Alt+Shift+Right"]
  - command: "move up"
    bindings: ["LWin+Shift+Up", "Alt+Shift+Up"]
  - command: "move down"
    bindings: ["LWin+Shift+Down", "Alt+Shift+Down"]

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "Alt+R"

  # As an alternative to the resize keybindings above, resize mode enables resizing via
  # HJKL or arrow keys. The binding mode is defined above with the name "resize".
  - command: "binding mode resize"
    binding: "LWin+R"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "Alt+V"

  # Change tiling direction. This determines where new tiling windows will be inserted.
  - command: "tiling direction toggle"
    binding: "LWin+V"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "Alt+Space"

  # Change focus between floating / tiling windows.
  - command: "focus mode toggle"
    binding: "LWin+Alt+Space"

  # Change the focused window to be floating / tiling.
  - command: "toggle floating"
    binding: "Alt+Shift+Space"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "Alt+X"

  # Change the focused window to be maximized / unmaximized.
  - command: "toggle maximized"
    binding: "LWin+F"

  # Minimize focused window.
  - command: "set minimized"
    binding: "Alt+M"

  # Close focused window.
  - command: "close"
    binding: "Alt+Shift+Q"

  # Close focused window.
  - command: "close"
    binding: "LWin+Shift+Q"

  # Kill GlazeWM process safely.
  - command: "exit wm"
    binding: "Alt+Shift+E"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "Alt+Shift+R"

  # Re-evaluate configuration file.
  - command: "reload config"
    binding: "LWin+Shift+R"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  #- command: "exec wt"
  #  binding: "Alt+Enter"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  - command: "exec wt"
    binding: "LWin+Enter"

  # Launch CMD terminal (alternatively `exec wt` or `exec %ProgramFiles%/Git/git-bash.exe`
  # to start Windows Terminal and Git Bash respectively.
  #- command: "exec"
  #  binding: "LWin"

  # Focus the workspace that last had focus.
  - command: "focus workspace recent"
    binding: "Alt+Y"

  # Focus the next/previous workspace defined in `workspaces` config.
  - command: "focus workspace next"
    binding: "Alt+T"
  - command: "focus workspace prev"
    binding: "Alt+Shift+T"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "LWin+1"
  - command: "focus workspace 2"
    binding: "LWin+2"
  - command: "focus workspace 3"
    binding: "LWin+3"
  - command: "focus workspace 4"
    binding: "LWin+4"
  - command: "focus workspace 5"
    binding: "LWin+5"
  - command: "focus workspace 6"
    binding: "LWin+6"
  - command: "focus workspace 7"
    binding: "LWin+7"
  - command: "focus workspace 8"
    binding: "LWin+8"
  - command: "focus workspace 9"
    binding: "LWin+9"

  # Change focus to a workspace defined in `workspaces` config.
  - command: "focus workspace 1"
    binding: "Control+Alt+1"
  - command: "focus workspace 2"
    binding: "Control+Alt+2"
  - command: "focus workspace 3"
    binding: "Control+Alt+3"
  - command: "focus workspace 4"
    binding: "Control+Alt+4"
  - command: "focus workspace 5"
    binding: "Control+Alt+5"
  - command: "focus workspace 6"
    binding: "Control+Alt+6"
  - command: "focus workspace 7"
    binding: "Control+Alt+7"
  - command: "focus workspace 8"
    binding: "Control+Alt+8"
  - command: "focus workspace 9"
    binding: "Control+Alt+9"

  # Move focused workspace to a monitor in a given direction.
  #- command: "move workspace left"
  #  binding: "Alt+A"
  #- command: "move workspace right"
  #  binding: "Alt+F"
  #- command: "move workspace up"
  #  binding: "Alt+D"
  #- command: "move workspace down"
  #  binding: "Alt+S"

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1", "focus workspace 1"]
    binding: "Alt+Shift+1"
  - commands: ["move to workspace 2", "focus workspace 2"]
    binding: "Alt+Shift+2"
  - commands: ["move to workspace 3", "focus workspace 3"]
    binding: "Alt+Shift+3"
  - commands: ["move to workspace 4", "focus workspace 4"]
    binding: "Alt+Shift+4"
  - commands: ["move to workspace 5", "focus workspace 5"]
    binding: "Alt+Shift+5"
  - commands: ["move to workspace 6", "focus workspace 6"]
    binding: "Alt+Shift+6"
  - commands: ["move to workspace 7", "focus workspace 7"]
    binding: "Alt+Shift+7"
  - commands: ["move to workspace 8", "focus workspace 8"]
    binding: "Alt+Shift+8"
  - commands: ["move to workspace 9", "focus workspace 9"]
    bindings: ["Alt+Shift+9"]

  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ["move to workspace 1"]
    binding: "LWin+Shift+1"
  - commands: ["move to workspace 2"]
    binding: "LWin+Shift+2"
  - commands: ["move to workspace 3"]
    binding: "LWin+Shift+3"
  - commands: ["move to workspace 4"]
    binding: "LWin+Shift+4"
  - commands: ["move to workspace 5"]
    binding: "LWin+Shift+5"
  - commands: ["move to workspace 6"]
    binding: "LWin+Shift+6"
  - commands: ["move to workspace 7"]
    binding: "LWin+Shift+7"
  - commands: ["move to workspace 8"]
    binding: "LWin+Shift+8"
  - commands: ["move to workspace 9"]
    bindings: ["LWin+Shift+9"]
